# configs/grpc.yaml
server:
  address: ":50051"
  max_conns: 10000
  keepalive:
    enabled: true
    max_connection_idle: 5 # 空闲连接最长保持时间 单位: 分钟
    max_connection_age: 10 # 连接在接收到关闭信号，还能保持的时间 单位: 分钟
    max_connection_age_grace: 5 # MaxConnectionAgeGrace是MaxConnectionAge之后的一个附加周期, 过了这个周期强制关闭 单位: 秒
    time: 2 # 服务器2小时后发送ping，判断是否连接存活 单位: 小时
    timeout: 20 # 在Time参数时间后，发送了ping后，如果20秒内没有收到客户端的pong，则关闭连接 单位: 秒
  tls:
    enabled: false
    cert: "certs/server.crt"
    key: "certs/server.key"