// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"Taurus/internal/controller"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	validateCtrl := &controller.ValidateCtrl{}
	traceCtrl := &controller.TraceCtrl{}
	midCtrl := &controller.MidCtrl{}
	injector := &Injector{
		ValidateCtrl: validateCtrl,
		TraceCtrl:    traceCtrl,
		MidCtrl:      midCtrl,
	}
	return injector, func() {
	}, nil
}
