databases:
  - name: "kf_ai"      # 数据库名称
    type: "mysql"      # 数据库类型 (postgres, mysql, sqlite)
    host: "db"         # 数据库主机
    port: 3306         # 数据库端口
    user: "apps"       # 数据库用户名
    password: "apps"   # 数据库密码
    dbname: "kf_ai"    # 数据库名称
    sslmode: "disable" # SSL 模式 (仅适用于 PostgreSQL)
    dsn: "apps:apps@tcp(db:3306)/kf_ai?charset=utf8mb4&parseTime=True&loc=Local"  # 可选，直接提供完整的 DSN 字符串（优先级高于其他字段）
    logger:                   # 日志配置
      log_file_path: "logs/db/kf_ai.log" # 日志文件路径（为空时输出到控制台）
      max_size: 10            # 单个日志文件的最大大小（单位：MB） , 当日志文件路径不为空时生效
      max_backups: 5          # 保留的旧日志文件的最大数量 , 当日志文件路径不为空时生效
      max_age: 30             # 日志文件的最大保存天数 , 当日志文件路径不为空时生效
      compress: true          # 是否压缩旧日志文件 , 当日志文件路径不为空时生效
      log_level: "info"       # 日志等级 (silent（静默）、error（错误）、warn（警告）、info（信息）) 
      slow_threshold: 200     # 慢查询阈值（单位：毫秒）

  - name: "kf_ai_test"
    type: "mysql"
    host: "db"  # 数据库主机， 这里设置的db是因为docker-compose.yml中设置的db服务名称, 都在同一个网络的情况下
    port: 3306
    user: "apps"
    password: "apps"
    dbname: "kf_ai"
    dsn: "apps:apps@tcp(db:3306)/kf_ai?charset=utf8mb4&parseTime=True&loc=Local"
    logger:
      log_file_path: "logs/db/kf_ai_test.log"       # 输出到控制台
      max_size: 20
      max_backups: 3
      max_age: 15
      compress: false
      log_level: "warn"
      slow_threshold: 500